import atomicHabits from "./assets/atomichabits.jpg";
import iphone from "./assets/iphone.jpg";
import speaker from "./assets/speaker.jpg";
import monitor from "./assets/monitor.jpg";
import echo from "./assets/echo.jpg";
import ipad from "./assets/ipad.jpg";
import lenovo from "./assets/lenovo.jpg";
import canon from "./assets/canon.jpeg";
import pixel from "./assets/pixel.jpeg";
import airpods from "./assets/airpods.jpeg";
import kindle from "./assets/kindle.jpeg";
import macbook from "./assets/macbook.jpeg";
import fitbit from "./assets/fitbit.jpeg";
import nintendo from "./assets/nintendo.jpeg";
import xbox from "./assets/xbox.jpeg";
import sonyheadphones from "./assets/sonyheadphones.jpg";
import boseheadphones from "./assets/boseheadphones.jpg";
import garminfenix from "./assets/garminfenix.jpg";
import djimavic3 from "./assets/djimavic3.jpg";
import razerblade from "./assets/razerblade.jpg";
import bosesoundbar from "./assets/bosesoundbar.jpg";
import logitechmouse from "./assets/logitechmouse.jpg";
import sennheiserheadphones from "./assets/sennheiserheadphones.jpg";
import ankerpowerbank from "./assets/ankerpowerbank.jpg";
import boseearpods from "./assets/boseearpods.jpg";
import sonytvx950h from "./assets/sonytvx950h.jpg";
import levis501 from "./assets/levis501.jpg";
import dysonv15 from "./assets/dysonv15.jpg";
import nespressovertuo from "./assets/nespressovertuo.jpg";
import instantpotduocrisp from "./assets/instantpotduocrisp.jpg";
import vitamixexplorian from "./assets/vitamixexplorian.jpg";
import kitchenaidartisan from "./assets/kitchenaidartisan.jpg";
import calphalonnonstick from "./assets/calphalonnonstick.jpg";
import caspermattress from "./assets/caspermattress.jpg";
import patagonianano from "./assets/patagonianano.jpg";
import yetirambler from "./assets/yetirambler.jpg";

let inventory = [
  {
    id: 864998723,
    title: "Atomic Habits : The life-changing million copy",
    image: atomicHabits,
    price: 522,
    rating: 5,
    keywords: [
      "Atomic Habits",
      "James Clear",
      "habit formation",
      "habit change",
      "self-improvement",
      "personal development",
      "productivity",
      "behavior change",
      "lifestyle",
      "million copy bestseller",
      "life-changing",
      "practical guide",
      "evidence-based",
      "habits book",
      "habit building",
      "habit breaking",
    ],
  },
  {
    id: 561157539,
    title: "Apple iPhone 15 Pro (256 GB) - Natural Titanium",
    image: iphone,
    price: 137990,
    rating: 4,
    keywords: [
      "iPhone 15 Pro",
      "Apple iPhone 15 Pro",
      "iPhone 15 Pro 256GB",
      "iPhone 15 Pro Natural Titanium",
      "Apple smartphone",
      "flagship smartphone",
      "premium smartphone",
      "A17 Bionic chip",
      "48MP camera",
      "Dynamic Island",
      "Always-On display",
      "ProMotion display",
      "Face ID",
      "iPhone",
      "Apple",
      "5G",
      "256GB storage",
      "titanium body",
      "lightweight design",
      "high-end phone",
      "Apple tech",
      "iOS 17",
      "mobile photography",
      "mobile performance",
    ],
  },
  {
    id: 741258974,
    title:
      "Marshall Kilburn II Portable Bluetooth Speaker with 20+ hours of portable playtime, (360° sound), Water-Resistant (IPX2) – Black & Brass.",
    image: speaker,
    price: 25999,
    rating: 3,
    keywords: [
      "Marshall Kilburn II",
      "Marshall Kilburn II speaker",
      "Marshall Kilburn II Bluetooth speaker",
      "Marshall portable speaker",
      "Marshall wireless speaker",
      "Kilburn II",
      "Marshall 360 degree sound",
      "Marshall IPX2",
      "Marshall water-resistant speaker",
      "Marshall black and brass",
      "portable Bluetooth speaker",
      "wireless speaker",
      "20 hour battery life",
      "20+ hours playtime",
      "360 degree audio",
      "IPX2 water-resistant",
      "black and brass design",
      "Marshall sound quality",
      "Marshall design",
      "Marshall audio",
      "speaker",
      "audio",
      "bluetooth",
    ],
  },
  {
    id: 452785543,
    title:
      "Amazon Echo Dot 4th Gen with clock | Smart speaker with powerful bass, LED display and Alexa (Blue)",
    image: echo,
    price: 5499,
    rating: 3,
    keywords: [
      "Amazon Echo Dot",
      "smart speaker",
      "Alexa",
      "4th generation",
      "clock",
      "LED display",
      "powerful bass",
      "voice control",
      "hands-free",
      "smart home",
      "blue color",
      "compact design",
      "easy setup",
      "Alexa skills",
      "music streaming",
      "smart home control",
      "voice assistant",
      "Amazon Echo",
      "Amazon Alexa",
      "home automation",
      "smart tech",
      "smart device",
      "speaker",
    ],
  },
  {
    id: 965412574,
    title:
      "Apple iPad Pro 11″ (M4): Ultra Retina XDR Display, 256GB, Landscape 12MP Front Camera / 12MP Back Camera, LiDAR Scanner, Wi-Fi 6E, Face ID, All-Day Battery Life, Standard Glass — Space Black",
    image: ipad,
    price: 97099,
    rating: 4,
    keywords: [
      "iPad Pro",
      "Apple iPad Pro",
      "11 inch",
      "M4 chip",
      "Retina XDR display",
      "256GB storage",
      "12MP front camera",
      "12MP back camera",
      "LiDAR scanner",
      "Wi-Fi 6E",
      "Face ID",
      "all-day battery",
      "glass design",
      "space black color",
      "Apple tablet",
      "powerful performance",
      "augmented reality",
      "professional use",
      "premium tablet",
      "Apple Pencil",
      "iPadOS",
      "Apple tech",
      "tablet",
      "iPad",
    ],
  },
  {
    id: 324581268,
    title:
      "Samsung 49-inch(124.4cm) Odyssey OLED G9 Dual QHD, 240Hz, 0.03ms Curved Gaming Monitor, USB Hub, HAS, Neo Quantum Processor, Smart TV, AMD FreeSync Premium Pro (LS49CG950SWXXL, Black)",
    image: monitor,
    price: 166099,
    rating: 4,
    keywords: [
      "Samsung Odyssey OLED G9",
      "gaming monitor",
      "49 inch",
      "dual QHD resolution",
      "240Hz refresh rate",
      "0.03ms response time",
      "curved display",
      "USB hub",
      "height adjustable stand",
      "Neo Quantum processor",
      "smart TV features",
      "AMD FreeSync Premium Pro",
      "immersive gaming",
      "high-performance",
      "low latency",
      "black color",
      "Samsung monitor",
      "gaming",
      "desktop",
      "computer",
      "monitor",
    ],
  },
  {
    id: 874533698,
    title:
      "Lenovo IdeaPad Slim 1 AMD Ryzen 5 5500U 15.6 HD Thin and Light Laptop (16GB/512GB SSD/Windows 11 Home/MS Office 2021/1Yr ADP Free/Cloud Grey/1.61Kg), 82R400ERIN",
    image: lenovo,
    price: 38990,
    rating: 4,
    keywords: [
      "Lenovo IdeaPad Slim 1",
      "laptop",
      "AMD Ryzen 5 5500U",
      "15.6 inch HD display",
      "thin and light design",
      "16GB RAM",
      "512GB SSD",
      "Windows 11 Home",
      "Microsoft Office 2021",
      "1-year ADP",
      "cloud grey color",
      "1.61kg weight",
      "AMD Radeon graphics",
      "USB-C",
      "long battery life",
      "affordable price",
      "Lenovo laptop",
      "productivity",
      "windows",
    ],
  },
  {
    id: 231044852,
    title:
      "Canon EOS R10 24.2MP RF-S18-150mm f/4.5-6.3 IS STM Mirrorless Camera (APS-C Sensor, 4K UHD Video) for Wedding & Content creators – Black",
    image: canon,
    price: 97679,
    rating: 4,
    keywords: [
      "Canon EOS R10",
      "mirrorless camera",
      "24.2MP APS-C sensor",
      "RF-S18-150mm lens",
      "4K UHD video",
      "wedding photography",
      "content creation",
      "vlogging",
      "DIGIC X processor",
      "eye detection AF",
      "high-speed continuous shooting",
      "3-inch vari-angle touchscreen",
      "built-in Wi-Fi and Bluetooth",
      "compact design",
      "black color",
      "camera",
      "photography",
      "Canon",
      "mirrorless",
      "content creation",
      "vlogging",
    ],
  },
  {
    id: 654789123,
    title: "Apple AirPods Pro (2nd Generation) with MagSafe Charging Case",
    image: airpods,
    price: 26999,
    rating: 5,
    keywords: [
      "AirPods Pro",
      "AirPods",
      "earphones",
      "wireless earphones",
      "Apple AirPods",
      "wireless earbuds",
      "noise cancellation",
      "transparency mode",
      "MagSafe",
      "charging case",
      "Apple audio",
      "iOS",
      "Bluetooth",
      "in-ear headphones",
      "active noise control",
      "spatial audio",
      "sweat and water resistant",
    ],
  },
  {
    id: 987654321,
    title:
      "Kindle Paperwhite (8 GB) – Now with a 6.8 display and adjustable warm light",
    image: kindle,
    price: 11999,
    rating: 4,
    keywords: [
      "Kindle Paperwhite",
      "e-reader",
      "kindle",
      "tablet",
      "e-book reader",
      "6.8 inch display",
      "adjustable warm light",
      "8GB storage",
      "e-ink display",
      "glare-free",
      "long battery life",
      "Kindle",
      "Amazon",
      "ebook",
      "reading",
      "portable",
      "lightweight",
    ],
  },
  {
    id: 147258369,
    title: "Apple MacBook Pro 13-inch with M2 chip",
    image: macbook,
    price: 119900,
    rating: 5,
    keywords: [
      "MacBook Pro",
      "Apple",
      "M2 chip",
      "laptop",
      "mac",
      "macbook",
      "Apple MacBook Pro",
      "13-inch laptop",
      "M2 chip",
      "Apple silicon",
      "macOS",
      "powerful performance",
      "long battery life",
      "Retina display",
      "thin and light design",
      "Apple laptop",
      "productivity",
      "creative work",
      "premium laptop",
      "aluminum unibody",
    ],
  },
  {
    id: 369852147,
    title:
      "Fitbit Sense Advanced Smartwatch with Tools for Heart Health, Stress Management & Skin Temperature Trends",
    image: fitbit,
    price: 22999,
    rating: 4,
    keywords: [
      "Fitbit Sense",
      "smartwatch",
      "fitness tracker",
      "heart health",
      "stress management",
      "skin temperature",
      "ECG",
      "EDA scan",
      "sleep tracking",
      "activity tracking",
      "exercise",
      "health monitoring",
      "wearable tech",
      "Fitbit",
      "wellness",
      "smartwatch",
      "health",
    ],
  },
  {
    id: 753951456,
    title: "Nintendo Switch OLED Model with White Joy-Con",
    image: nintendo,
    price: 34999,
    rating: 4,
    keywords: [
      "Nintendo Switch",
      "OLED model",
      "gaming console",
      "white Joy-Con",
      "handheld",
      "TV mode",
      "tabletop mode",
      "OLED display",
      "enhanced audio",
      "increased storage",
      "Nintendo",
      "gaming",
      "entertainment",
      "portable",
      "family friendly",
      "psp",
      "console",
    ],
  },
  {
    id: 951753456,
    title:
      "Google Pixel 7 Pro - Unlocked Android Smartphone - 5G - 128GB - Obsidian",
    image: pixel,
    price: 84999,
    rating: 5,
    keywords: [
      "Google Pixel 7 Pro",
      "Android smartphone",
      "5G",
      "128GB storage",
      "Obsidian color",
      "Google Tensor G2 chip",
      "triple camera system",
      "astrophotography",
      "face unlock",
      "water resistant",
      "Google",
      "Android",
      "mobile photography",
      "flagship phone",
      "unlocked",
      "smartphone",
      "Google Pixel",
      "phone",
      "google",
      "android",
    ],
  },
  {
    id: 159753456,
    title: "Xbox Series X Console",
    image: xbox,
    price: 49999,
    rating: 4,
    keywords: [
      "Xbox Series X",
      "gaming console",
      "4K gaming",
      "120fps",
      "ray tracing",
      "fast load times",
      "SSD storage",
      "Xbox",
      "Microsoft",
      "next-gen",
      "high-performance",
      "immersive gaming",
      "entertainment",
      "multimedia",
      "console",
      "gaming",
      "Xbox Game Pass",
      "Xbox Live",
    ],
  },
  {
    id: 456789012,
    title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
    image: sonyheadphones,
    price: 29990,
    rating: 5,
    keywords: [
      "Sony WH-1000XM5",
      "wireless headphones",
      "noise cancelling",
      "Bluetooth",
      "premium audio",
      "adaptive noise control",
      "LDAC codec",
      "touch controls",
      "long battery life",
      "comfortable design",
      "smart listening",
      "Sony audio",
      "high-end headphones",
      "immersive sound",
      "travel companion",
      "headphones",
      "music",
      "headphone",
    ],
  },
  {
    id: 678901234,
    title: "Bose Noise Cancelling Headphones 700",
    image: boseheadphones,
    price: 34500,
    rating: 4,
    keywords: [
      "Bose Noise Cancelling Headphones 700",
      "wireless headphones",
      "noise cancellation",
      "Bluetooth",
      "premium audio",
      "adjustable noise cancelling",
      "touch controls",
      "voice assistant",
      "long battery life",
      "sleek design",
      "Bose audio quality",
      "noise-free calls",
      "office use",
      "travel headphones",
      "active noise control",
      "headphones",
      "music",
      "premium",
      "tech",
    ],
  },
  {
    id: 901234567,
    title: "Garmin Fenix 7 Solar Multisport GPS Watch",
    image: garminfenix,
    price: 59990,
    rating: 4,
    keywords: [
      "Garmin Fenix 7",
      "multisport GPS watch",
      "solar-powered",
      "outdoor watch",
      "fitness tracking",
      "heart rate monitoring",
      "sleep tracking",
      "body battery",
      "training features",
      "navigation",
      "topographic maps",
      "rugged design",
      "long battery life",
      "Garmin smartwatch",
      "adventure sports",
      "fitness",
      "watch",
      "smartwatch",
    ],
  },
  {
    id: 234567890,
    title: "DJI Mavic 3 Cine Premium Combo Drone",
    image: djimavic3,
    price: 159990,
    rating: 5,
    keywords: [
      "DJI Mavic 3 Cine",
      "drone",
      "4/3 CMOS camera",
      "6K video",
      "10-bit D-Log",
      "Hasselblad camera",
      "obstacle avoidance",
      "ActiveTrack 5.0",
      "OcuSync 3.0",
      "long flight time",
      "premium combo",
      "professional photography",
      "cinematic video",
      "DJI technology",
      "aerial imaging",
      "drone",
      "professional",
      "dji",
    ],
  },
  {
    id: 345678901,
    title: "Razer Blade 15 Advanced Gaming Laptop",
    image: razerblade,
    price: 179990,
    rating: 4,
    keywords: [
      "Razer Blade 15",
      "gaming laptop",
      "advanced model",
      "15.6 inch display",
      "NVIDIA GeForce RTX 30 series",
      "Intel Core i9 processor",
      "16GB RAM",
      "1TB SSD",
      "4K OLED display",
      "120Hz refresh rate",
      "RGB keyboard",
      "vapor chamber cooling",
      "Thunderbolt 4",
      "premium design",
      "high-performance gaming",
      "laptop",
      "gaming",
      "razer",
    ],
  },
  {
    id: 456789012,
    title: "Bose Soundbar 700 with Alexa Built-in",
    image: bosesoundbar,
    price: 59990,
    rating: 4,
    keywords: [
      "Bose Soundbar 700",
      "smart soundbar",
      "Alexa built-in",
      "premium audio",
      "HDMI ARC",
      "Bluetooth",
      "Wi-Fi",
      "voice control",
      "room calibration",
      "dialogue enhancement",
      "surround sound",
      "sleek design",
      "smart home integration",
      "Bose sound quality",
      "home entertainment",
      "speaker",
      "music",
    ],
  },
  {
    id: 567890123,
    title: "Logitech MX Master 3 Advanced Wireless Mouse",
    image: logitechmouse,
    price: 7995,
    rating: 5,
    keywords: [
      "Logitech MX Master 3",
      "wireless mouse",
      "advanced features",
      "ergonomic design",
      "hyper-fast scroll wheel",
      "thumb wheel",
      "USB-C charging",
      "Bluetooth/Unifying receiver",
      "customizable buttons",
      "flow cross-computer control",
      "high-precision sensor",
      "productivity mouse",
      "Logitech quality",
      "office use",
      "creative work",
      "mouse",
      "accessories",
      "laptop",
    ],
  },
  {
    id: 678901234,
    title: "Sennheiser HD 6XX Series Open-Back Headphones",
    image: sennheiserheadphones,
    price: 14990,
    rating: 4,
    keywords: [
      "Sennheiser HD 6XX",
      "open-back headphones",
      "audiophile-grade",
      "dynamic drivers",
      "detailed sound",
      "wide soundstage",
      "comfortable fit",
      "velour earpads",
      "durable construction",
      "replaceable cable",
      "studio monitoring",
      "critical listening",
      "Sennheiser audio",
      "high-fidelity",
      "music enthusiasts",
      "headphones",
      "music",
      "gaming",
      "high end",
      "tech",
    ],
  },
  {
    id: 789012345,
    title: "Anker Powercore III Elite 25600 PD Power Bank",
    image: ankerpowerbank,
    price: 5999,
    rating: 4,
    keywords: [
      "Anker Powercore III Elite",
      "power bank",
      "25600mAh capacity",
      "USB-C Power Delivery",
      "fast charging",
      "high-density cells",
      "multiple charging ports",
      "safety protection",
      "compact design",
      "portable charger",
      "long-lasting battery",
      "Anker quality",
      "travel essential",
      "device charging",
      "emergency backup",
      "powerbank",
      "battery",
    ],
  },
  {
    id: 890123456,
    title: "Bose QuietComfort Earbuds II Wireless Noise Cancelling Earphones",
    image: boseearpods,
    price: 27990,
    rating: 5,
    keywords: [
      "Bose QuietComfort Earbuds II",
      "wireless earbuds",
      "noise cancelling",
      "Bluetooth",
      "customizable fit",
      "Aware Mode",
      "volume-optimized EQ",
      "IPX4 water resistance",
      "touch controls",
      "long battery life",
      "compact design",
      "Bose audio quality",
      "noise isolation",
      "ambient awareness",
      "comfortable in-ear experience",
      "earphones",
      "airpods",
      "bose",
      "music",
    ],
  },
  {
    id: 901234567,
    title: "Sony X950H 65-Inch 4K HDR LED Smart TV",
    image: sonytvx950h,
    price: 149990,
    rating: 4,
    keywords: [
      "Sony X950H",
      "4K HDR LED TV",
      "65-inch display",
      "smart TV",
      "Android TV",
      "X1 Ultimate processor",
      "4K HDR Processor X1",
      "Triluminos Display",
      "X-Wide Angle",
      "X-Motion Clarity",
      "Dolby Atmos",
      "Google Assistant",
      "Amazon Alexa",
      "premium home entertainment",
      "cinematic experience",
      "tv",
      "display",
      "sony",
    ],
  },
  {
    id: 159753789,
    title: "Levi's 501 Original Fit Jeans - Stonewash",
    image: levis501,
    price: 3499,
    rating: 4,
    keywords: [
      "Levi's 501",
      "original fit jeans",
      "stonewash",
      "denim",
      "classic style",
      "5-pocket design",
      "button fly",
      "cotton blend",
      "comfortable fit",
      "versatile",
      "Levi's quality",
      "casual wear",
      "everyday jeans",
      "timeless fashion",
      "men's clothing",
      "jeans",
      "clothes",
    ],
  },
  {
    id: 753951789,
    title: "Dyson V15 Detect Cordless Vacuum Cleaner",
    image: dysonv15,
    price: 54900,
    rating: 5,
    keywords: [
      "Dyson V15 Detect",
      "cordless vacuum",
      "powerful suction",
      "laser dust detection",
      "advanced filtration",
      "LCD display",
      "anti-tangle technology",
      "hygienic dirt emptying",
      "up to 60 minutes runtime",
      "lightweight design",
      "Dyson engineering",
      "deep cleaning",
      "hard floors",
      "carpets",
      "home cleaning",
      "cleaning",
      "vacuum",
    ],
  },
  {
    id: 951753789,
    title: "Nespresso Vertuo Next Coffee and Espresso Machine by Breville",
    image: nespressovertuo,
    price: 12990,
    rating: 4,
    keywords: [
      "Nespresso Vertuo Next",
      "coffee machine",
      "espresso machine",
      "Breville",
      "Centrifusion technology",
      "automatic blend recognition",
      "one-touch operation",
      "30oz water tank",
      "used capsule container",
      "fast brewing",
      "versatile drink sizes",
      "modern design",
      "barista-style coffee",
      "home cafe",
      "kitchen appliance",
      "coffee",
      "espresso",
    ],
  },
  {
    id: 159753951,
    title:
      "Instant Pot Duo Crisp 11-in-1 Electric Pressure Cooker with Air Fryer Lid",
    image: instantpotduocrisp,
    price: 13995,
    rating: 5,
    keywords: [
      "Instant Pot Duo Crisp",
      "pressure cooker",
      "air fryer",
      "11-in-1 multi-cooker",
      "large 8-quart capacity",
      "one-touch controls",
      "air fryer lid",
      "crisping",
      "dehydrating",
      "slow cooking",
      "rice cooking",
      "easy cleaning",
      "time-saving",
      "versatile cooking",
      "kitchen essential",
    ],
  },
  {
    id: 951753159,
    title:
      "Vitamix Explorian Blender, Professional-Grade, 64 oz. Low-Profile Container",
    image: vitamixexplorian,
    price: 34900,
    rating: 5,
    keywords: [
      "Vitamix Explorian",
      "professional blender",
      "64oz low-profile container",
      "high-performance motor",
      "variable speed control",
      "pulse feature",
      "self-cleaning",
      "BPA-free",
      "durable design",
      "smoothies",
      "soups",
      "nut butters",
      "frozen desserts",
      "culinary versatility",
      "kitchen appliance",
      "mixer",
      "grinder",
    ],
  },
  {
    id: 159753456,
    title: "KitchenAid Artisan Series 5-Quart Tilt-Head Stand Mixer",
    image: kitchenaidartisan,
    price: 39900,
    rating: 5,
    keywords: [
      "KitchenAid Artisan",
      "stand mixer",
      "5-quart capacity",
      "tilt-head design",
      "10 speed settings",
      "planetary mixing action",
      "stainless steel bowl",
      "tilt-head for easy access",
      "multiple attachments",
      "powerful motor",
      "durable construction",
      "baking",
      "kneading",
      "whipping",
      "kitchen",
      "grinder",
      "mixer",
      "kitchen essential",
    ],
  },
  {
    id: 951753789,
    title:
      "Calphalon Premier Space Saving Nonstick Pots and Pans Set, 15 Piece",
    image: calphalonnonstick,
    price: 19999,
    rating: 4,
    keywords: [
      "Calphalon Premier",
      "nonstick cookware set",
      "15-piece",
      "space-saving design",
      "hard-anodized aluminum",
      "PFOA-free",
      "oven safe",
      "dishwasher safe",
      "comfortable handles",
      "glass lids",
      "even heating",
      "durable construction",
      "kitchen organization",
      "cooking essentials",
      "home chef",
      "kitchen",
    ],
  },
  {
    id: 159753951,
    title: "Casper Original Foam Mattress, Supportive & Breathable",
    image: caspermattress,
    price: 44900,
    rating: 4,
    keywords: [
      "Casper Original Foam Mattress",
      "memory foam",
      "supportive",
      "breathable",
      "pressure relief",
      "zoned support",
      "open-cell foam",
      "cooling technology",
      "motion isolation",
      "CertiPUR-US certified",
      "easy setup",
      "comfortable sleep",
      "back support",
      "sleep quality",
      "home furnishings",
      "bed",
      "comfort",
    ],
  },
  {
    id: 951753159,
    title: "Patagonia Nano Puff Insulated Jacket - Men's",
    image: patagonianano,
    price: 12500,
    rating: 5,
    keywords: [
      "Patagonia Nano Puff",
      "insulated jacket",
      "men's",
      "lightweight",
      "water-resistant",
      "windproof",
      "recycled materials",
      "PrimaLoft Gold Insulation",
      "packable",
      "versatile",
      "outdoor apparel",
      "winter wear",
      "adventure",
      "sustainable fashion",
      "Patagonia quality",
      "jacket",
      "men",
      "clothing",
    ],
  },
  {
    id: 159753951,
    title: "Yeti Rambler 30oz Stainless Steel Vacuum Insulated Tumbler",
    image: yetirambler,
    price: 3499,
    rating: 4,
    keywords: [
      "Yeti Rambler",
      "30oz tumbler",
      "stainless steel",
      "vacuum insulated",
      "double-wall construction",
      "sweat-proof",
      "dishwasher safe",
      "durable",
      "keeps drinks hot or cold",
      "MagSlider lid",
      "outdoor gear",
      "travel mug",
      "camping",
      "Yeti quality",
      "lifestyle accessory",
      "coffee",
      "glass",
      "cup",
      "kitchen",
    ],
  },
];

export default inventory;
